name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0.0]

    steps:
      - name: 'Init repository'
        uses: actions/checkout@v2
      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Run eslint'
        run: ./node_modules/.bin/eslint .
      - name: 'Run tests'
        run: npm test
      - name: 'Set up Git user'
        run: |
          git config --global user.email "bendafischulmann@gmail.com"
          git config --global user.name "Antoine Bendafi-Schulmann"
      - name: 'Bump version and publish'
        run: |
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
